package uc15projetoatividade4;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class TelaCliente extends javax.swing.JFrame {

    private List<Cliente> clienteList = new ArrayList<>();

    public TelaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButtonCadastrarCliente = new javax.swing.JButton();
        jButtonPesquisarCliente = new javax.swing.JButton();
        jButtonLimparTela = new javax.swing.JButton();
        jTextFieldIdCliente = new javax.swing.JTextField();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jTextFieldCnpjCliente = new javax.swing.JTextField();
        jTextFieldEnderecoCliente = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 51, 0));
        jLabel1.setText("      ** CLIENTE **");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 190, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 0, 51));
        jLabel3.setText("NOME:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 0, 51));
        jLabel4.setText("CNPJ:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 0, 51));
        jLabel5.setText("ENDEREÇO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jButtonCadastrarCliente.setBackground(new java.awt.Color(255, 255, 153));
        jButtonCadastrarCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonCadastrarCliente.setForeground(new java.awt.Color(153, 0, 0));
        jButtonCadastrarCliente.setText("CADASTRAR");
        jButtonCadastrarCliente.setToolTipText("Clique aqui para Salvar as informações do cliente.");
        jButtonCadastrarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 130, 30));

        jButtonPesquisarCliente.setBackground(new java.awt.Color(255, 255, 153));
        jButtonPesquisarCliente.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonPesquisarCliente.setForeground(new java.awt.Color(153, 0, 0));
        jButtonPesquisarCliente.setText("PESQUISAR");
        jButtonPesquisarCliente.setToolTipText("Clique aqui para pesquisar algum cadastro.");
        jButtonPesquisarCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonPesquisarCliente.setEnabled(false);
        jButtonPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPesquisarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 120, 30));

        jButtonLimparTela.setBackground(new java.awt.Color(255, 255, 153));
        jButtonLimparTela.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButtonLimparTela.setForeground(new java.awt.Color(153, 0, 0));
        jButtonLimparTela.setText("LIMPAR");
        jButtonLimparTela.setToolTipText("Clique aqui para limpar os dados da tela.");
        jButtonLimparTela.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonLimparTela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparTelaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLimparTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 120, 30));
        jPanel1.add(jTextFieldIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 230, -1));
        jTextFieldIdCliente.getAccessibleContext().setAccessibleName("");
        jTextFieldIdCliente.getAccessibleContext().setAccessibleDescription("");

        jTextFieldNomeCliente.setToolTipText("Digite aqui o nome do cliente.");
        jPanel1.add(jTextFieldNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 230, -1));
        jTextFieldNomeCliente.getAccessibleContext().setAccessibleName("");
        jTextFieldNomeCliente.getAccessibleContext().setAccessibleDescription("");

        jTextFieldCnpjCliente.setToolTipText("Digite aqui o CNPJ do cliente.");
        jPanel1.add(jTextFieldCnpjCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 230, -1));

        jTextFieldEnderecoCliente.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldEnderecoCliente.setToolTipText("Digite aqui o Endereço do cliente.");
        jTextFieldEnderecoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(jTextFieldEnderecoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 230, 80));

        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jMenuItem1.setText("Tela Inicial");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonLimparTelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparTelaActionPerformed
        // TODO add your handling code here:
        jTextFieldIdCliente.setText("");
        jTextFieldNomeCliente.setText("");
        jTextFieldCnpjCliente.setText("");
        jTextFieldEnderecoCliente.setText("");

    }//GEN-LAST:event_jButtonLimparTelaActionPerformed

    private void jButtonCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarClienteActionPerformed
        // TODO add your handling code here:

        inserirCliente(getCliente());

        JOptionPane.showMessageDialog(null, "Cliente cadastrado com sucesso!");

        jTextFieldIdCliente.setText("");
        jTextFieldNomeCliente.setText("");
        jTextFieldCnpjCliente.setText("");
        jTextFieldEnderecoCliente.setText("");

    }//GEN-LAST:event_jButtonCadastrarClienteActionPerformed

    private void jButtonPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisarClienteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarCliente;
    private javax.swing.JButton jButtonLimparTela;
    private javax.swing.JButton jButtonPesquisarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCnpjCliente;
    private javax.swing.JTextField jTextFieldEnderecoCliente;
    private javax.swing.JTextField jTextFieldIdCliente;
    private javax.swing.JTextField jTextFieldNomeCliente;
    // End of variables declaration//GEN-END:variables

    public Cliente getCliente() {

        Cliente cliente = new Cliente();

        cliente.setId(jTextFieldIdCliente.getText());
        cliente.setNomeCliente(jTextFieldNomeCliente.getText());
        cliente.setCNPJCliente(jTextFieldCnpjCliente.getText());
        cliente.setEnderecoCliente(jTextFieldEnderecoCliente.getText());

        return cliente;
    }

    public void inserirCliente(Cliente cliente) {

        clienteList.add(cliente);

    }

}
